version: "3"

services:
  opsschool_dummy_app:
    image: localhost:5000/opsschool_dummy_app:latest
    ports:
      - "5005:5005"
    networks:
      - opsschool-dummy

    restart: always
    container_name: opsschool_dummy_app

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - opsschool-dummy
    depends_on:
      - opsschool_dummy_app

networks:
  opsschool-dummy:
